### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by monolithed** [coonsta/cache-polyfill#12]
1

```js
if (!Cache.prototype.add) { ....
```

It will throw an exception. You'd check the `Cache` before

2
```js
return Promise.resolve().then(function() {...
```

It can be replaced with:
```
return new Promise(function() {...
```

3
Where's [matchAll, match, put, delete, keys](https://developer.mozilla.org/ru/docs/Web/API/Cache) ?
https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#cache

4
`window.fetch` and `URL` are not implemented yet in the most browsers. You'd mention it.

5
Do you see https://github.com/slightlyoff/ServiceWorker? Why not use the one?

**Comment by jakearchibald** [comment]
This doesn't add the cache api to browsers that don't have it, it adds in missing methods to the cache API.
