### ISSUE TITLE
ignoreSearch option in cache.match() not working

### ISSUE THREAD

**Issue by ilancohen** [coonsta/cache-polyfill#13]
I tried, and couldn't get the 'ignoreSearch' option working at all.
For reference: https://developer.mozilla.org/en-US/docs/Web/API/Cache/match#Parameters

**Comment by NekR** [comment]
@ilancohen see this https://github.com/NekR/sw-cache-options

@jakearchibald should we close this?

**Comment by jakearchibald** [comment]
Sure, thanks!
