### ISSUE TITLE
Mark polyfill as deprecated

### ISSUE THREAD

**Issue by mathiasbynens** [coonsta/cache-polyfill#17]
As soon as Chrome 46 (check) and Opera 33 (~~soon~~ [_now_](https://dev.opera.com/blog/opera-33/)) are out, this polyfill isn’t needed anymore. \o/

**Comment by mathiasbynens** [comment]
Opera 33 is now stable. Let’s do this?

**Comment by jakearchibald** [comment]
Agreed. Will do this when I get a moment.

**Comment by NathanWalker** [comment]
Is this truly deprecated and no longer useful?

**Comment by jakearchibald** [comment]
Yes. Chrome stable now supports addAll

**Comment by dandv** [comment]
@jakearchibald: should the entry at https://jakearchibald.github.io/isserviceworkerready/ be updated as well?

**Comment by jakearchibald** [comment]
Yeah, I'll try and get these updated tomorrow, keep getting distracted.

**Comment by AStoker** [comment]
Did this polyfill work for Safari and IE as well? We're hunting for a polyfill to use for those browsers.

**Comment by jakearchibald** [comment]
There's an IDB version in the history of this project, but it still
required fetch, Request, and Response.

**Comment by AStoker** [comment]
What was that branch name? There appear to be a few branches. This is something that would be fantastic for our company, but we need to support Safari and IE as well as Chrome and Firefox.

**Comment by NekR** [comment]
> As soon as Chrome 46 (check) and Opera 33 (soon now) are out, this polyfill isn’t needed anymore. \o/

This actually sounds interesting. Chrome now supports 98% of ES2015, so, should all es6 transpilers be deprecated once it reaches 100%?

I see in the logs that people are using Chrome 40 everyday, so it's a wrong assumption that once fixed version is release--polyfill isn't needed anymore.
