### ISSUE TITLE
Detect duplicated resources (catch TypeError exception).

### ISSUE THREAD

**Issue by pdorgambide** [coonsta/cache-polyfill#2]
By error a had duplicated resources  but the cache not show any error (console, ...). I saw that the cachedb check  this and throw an exception TypeError. I changed the ```addAll``` to notify about it:
```
CacheProto.addAll = function(requests) {
  requests = requests.map(castToRequest);
  
  Promise.all(
	 requests.map(function(request) {
	     return fetch(request);
	})
  ).then(function(responses) {
    return cacheDB.put(this._origin, this._name, responses.map(function(response, i) {
      return [requests[i], response];
    }));
  }.bind(this)).catch(function(err){ 
	  console.log(err);
  });
};
```
Once time a fix the duplicated I detect that Response don't has ```asBlob``` property and changed
```return item[1].asBlob ? item[1].asBlob() : item[1].body.asBlob();```
to
```return item[1].blob ? item[1].blob() : item[1].body.asBlob();```

I hope that will be right and helpful.

**Comment by jakearchibald** [comment]
Sorry for the slow response! In what way was the resource a duplicate? Same URL?
