### ISSUE TITLE
addAll( request, callback) to get more control about caching a bulk of responses.

### ISSUE THREAD

**Issue by pdorgambide** [coonsta/cache-polyfill#8]
I think that It will be useful to add a callback function (function(response)) as parameter to the cache.addAll(requests,callback), this allow get more control over the responses and  decide which will be cached, i.e. if response.status < 400 not store on cached.
This callback could return true/false to control what response is valid to be cached.
Thanks, great work,

**Comment by jakearchibald** [comment]
This is to do with the spec rather than the polyfill. See https://github.com/slightlyoff/ServiceWorker/issues/407
